on: 
  # Trigger sonarqube analysis when pushing in to develop or pull requests, and when creating a pull request. 
  push:
    branches:
      - develop
  pull_request:
      types: [opened, synchronize, reopened]
name: SonarQube Analysis
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@develop
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@develop
      with:
        host: 'http://172.29.20.40:9000'
        login: 'admin'
        password: 'admin'