on: 
  # Trigger sonarqube analysis when pushing in to develop or pull requests, and when creating a pull request. 
  push:
    branches:
      - develop
  pull_request:
      branches: [develop]
      types: [opened, synchronize, reopened]
name: SonarQube Analysis
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'develop'
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_USERNAME }}
        password: ${{ secrets.SONARQUBE_PASSWORD }}