on: 
  # Trigger sonarqube analysis when pushing in to develop or pull requests, and when creating a pull request. 
  push:
    branches:
      - develop
  pull_request:
      branches: [develop]
      types: [opened, synchronize, reopened]
name: SonarQube Analysis
jobs:
  sonarQubeScan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: run sonar scanner
      uses: mathrix-education/sonar-scanner@master
      with:
        version: 'latest' # required
        typescript: false
        scan: true
        args: --debug -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }} -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }}